# Generated by Django 4.0.2 on 2022-02-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_video_simlilar_contentmodel_video_similar'),
        ('user', '0002_remove_usermodel_wishlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='wishList',
            field=models.ManyToManyField(to='content.ContentModel'),
        ),
    ]
