# Generated by Django 4.0.2 on 2022-02-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_video_simlilar_contentmodel_video_similar'),
        ('user', '0004_alter_usermodel_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='wishList',
            field=models.ManyToManyField(blank=True, default=None, related_name='wishList', to='content.ContentModel'),
        ),
    ]
