# Generated by Django 4.0.1 on 2022-02-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='category',
            name='house',
        ),
        migrations.RemoveField(
            model_name='category',
            name='workout',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='자취방구하기', max_length=50),
            preserve_default=False,
        ),
    ]
