# Generated by Django 4.0.2 on 2022-02-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentmodel',
            old_name='video_simlilar',
            new_name='video_similar',
        ),
    ]
